<a href="https://colab.research.google.com/github/Jain-Dixon/MACHINE-LEARNING-WORKS/blob/main/assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
data=pd.read_csv('/content/employee.csv')
data.head()

            name   age   income gender  department grade  performance_score
0    Allen Smith  45.0      NaN    NaN  Operations    G3                723
1        S Kumar   NaN  16000.0      F     Finance    G0                520
2    Jack Morgan  32.0  35000.0      M     Finance    G2                674
3      Ying Chin  45.0  65000.0      F       Sales    G3                556
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2                711

In [5]:
data.tail()

            name   age   income gender  department grade  performance_score
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2                711
5  Satyam Sharma   NaN  62000.0    NaN       Sales    G3                649
6   James Authur  54.0      NaN      F  Operations    G3                 53
7     Josh Wills  54.0  52000.0      F     Finance    G3                901
8       Leo Duck  23.0  98000.0      M       Sales    G4                709

In [6]:
data.shape

(9, 7)

In [7]:
import pandas as pd

df = pd.read_csv("/content/employee.csv")
df = df.set_index("name")
print(df)

                age   income gender  department grade  performance_score
name
Allen Smith    45.0      NaN    NaN  Operations    G3                723
S Kumar         NaN  16000.0      F     Finance    G0                520
Jack Morgan    32.0  35000.0      M     Finance    G2                674
Ying Chin      45.0  65000.0      F       Sales    G3                556
Dheeraj Patel  30.0  42000.0      F  Operations    G2                711
Satyam Sharma   NaN  62000.0    NaN       Sales    G3                649
James Authur   54.0      NaN      F  Operations    G3                 53
Josh Wills     54.0  52000.0      F     Finance    G3                901
Leo Duck       23.0  98000.0      M       Sales    G4                709

In [8]:
import pandas as pd

df = pd.read_csv("/content/employee.csv")

high_performers = df[df["performance_score"] > 700]
print(high_performers)

            name   age   income gender  department grade  performance_score
0    Allen Smith  45.0      NaN    NaN  Operations    G3                723
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2                711
7     Josh Wills  54.0  52000.0      F     Finance    G3                901
8       Leo Duck  23.0  98000.0      M       Sales    G4                709

In [9]:
filtered = df[df["performance_score"].between(501, 699)]
print(filtered)

            name   age   income gender department grade  performance_score
1        S Kumar   NaN  16000.0      F    Finance    G0                520
2    Jack Morgan  32.0  35000.0      M    Finance    G2                674
3      Ying Chin  45.0  65000.0      F      Sales    G3                556
5  Satyam Sharma   NaN  62000.0    NaN      Sales    G3                649

In [10]:
print(df.isnull().sum())

name                 0
age                  2
income               2
gender               2
department           0
grade                0
performance_score    0
dtype: int64

In [11]:
Q1=np.percentile(data['performance_score'],25,interpolation='midpoint')
Q2=np.percentile(data['performance_score'],50,interpolation='midpoint')
Q3=np.percentile(data['performance_score'],75,interpolation='midpoint')

In [12]:
IQR = Q3 - Q1
low_lim=Q1 - 1.5*IQR
up_lim=Q3 + 1.5*IQR

In [13]:
outlier = []
for x in data['performance_score']:
  if ((x > up_lim) or (x < low_lim)):
    outlier.append(x)
print(outlier)

[53]

In [14]:
df['gender'].value_counts(dropna=False)

gender
F      5
NaN    2
M      2
Name: count, dtype: int64